services:
  dev:
    build:
      context: '.'
      dockerfile: './Dockerfile'
      target: prod
    volumes:
      - type: bind
        source: ./
        target: /app/
    tty: true
  prod:
    image: ghcr.io/tsukina-7mochi/discord-slot-bot:latest
    volumes:
      - type: bind
        source: ./
        target: /app/
    tty: true

